### Lunamatic configuration ###

#Choose plugin language, you can find all of supported translations in plugins/lunamatic/lang
#You can create your own translations, by copying the English one, renaming and translating the language file.
#Contribute your translations here: https://github.com/Ifiht/Lunatic
#Valid options: en_US, cs_CZ, de_DE
lang: "en_US"

# Choose which moon effects to enable
fullMoonEnabled: true
newMoonEnabled: true
## Ignored unless fullMoonEnabled == true
harvestMoonEnabled: true
## Ignored unless newMoonEnabled == true
bloodMoonEnabled: true
## Enable Vex spawning while blood moon is active
bloodMoonSpawnVex: true

# Chance for Blood and Harvest Moons ###
# This sets the number of sides in the dice roll,
# e.g. 2 = coin-toss (50/50), 6 = normal die (17% chance)
bloodMoonDieSides: 2
harvestMoonDieSides: 2
# Set worlds to disable moon-effects on ###
# by design both nether & the_end cannot have moon effects
disabledWorlds:
  - world_nether
  - world_the_end
# Do you want to check for updates at server start?
checkForUpdates: true